<?php

declare(strict_types=1);

use yii\db\Expression;
use yii\db\Migration;

/**
 * Squashed migration combining all previous migrations.
 *
 * This migration was auto-generated by squash-migrations command.
 *
 * Squashed migrations:
 *   - m241220_000001_create_industry_config_table.php
 *   - m241220_000002_create_collection_run_table.php
 *   - m241220_000003_create_collection_error_table.php
 *   - m241220_000004_create_source_block_table.php
 *   - m251229_042630_add_partial_status_to_collection_run.php
 *   - m251229_235826_rename_config_yaml_to_config_json.php
 */
class m251230_231040_squashed_schema extends Migration
{
    public function safeUp(): void
    {
        // Table: collection_error
        $this->createTable('{{%collection_error}}', [
            'id' => $this->primaryKey(),
            'collection_run_id' => $this->integer()->notNull(),
            'severity' => $this->string(20)->notNull()->defaultValue('error'),
            'error_code' => $this->string(64)->notNull(),
            'error_message' => $this->text()->notNull(),
            'error_path' => $this->string(255)->defaultValue(null),
            'ticker' => $this->string(20)->defaultValue(null),
            'created_at' => $this->timestamp()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
        ]);

        // Table: collection_run
        $this->createTable('{{%collection_run}}', [
            'id' => $this->primaryKey(),
            'industry_id' => $this->string(64)->notNull(),
            'datapack_id' => $this->string(36)->notNull(),
            'status' => $this->string(20)->notNull()->defaultValue('pending'),
            'started_at' => $this->timestamp()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
            'completed_at' => $this->timestamp()->defaultValue(null),
            'companies_total' => $this->integer()->notNull()->defaultValue(0),
            'companies_success' => $this->integer()->notNull()->defaultValue(0),
            'companies_failed' => $this->integer()->notNull()->defaultValue(0),
            'gate_passed' => $this->tinyInteger()->defaultValue(null),
            'error_count' => $this->integer()->notNull()->defaultValue(0),
            'warning_count' => $this->integer()->notNull()->defaultValue(0),
            'file_path' => $this->string(512)->defaultValue(null),
            'file_size_bytes' => $this->bigInteger()->defaultValue(null),
            'duration_seconds' => $this->integer()->defaultValue(null),
        ]);

        $this->createIndex('datapack_id', '{{%collection_run}}', ['datapack_id'], true);

        // Table: industry_config
        $this->createTable('{{%industry_config}}', [
            'id' => $this->primaryKey(),
            'industry_id' => $this->string(64)->notNull(),
            'name' => $this->string(255)->notNull(),
            'config_json' => $this->text()->notNull(),
            'is_active' => $this->tinyInteger()->notNull()->defaultValue(1),
            'created_at' => $this->timestamp()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
            'updated_at' => $this->timestamp()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
        ]);

        $this->createIndex('industry_id', '{{%industry_config}}', ['industry_id'], true);

        // Table: source_block
        $this->createTable('{{%source_block}}', [
            'id' => $this->primaryKey(),
            'domain' => $this->string(255)->notNull(),
            'blocked_at' => $this->timestamp()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
            'blocked_until' => $this->timestamp()->notNull(),
            'consecutive_count' => $this->integer()->notNull()->defaultValue(1),
            'last_status_code' => $this->integer()->defaultValue(null),
            'last_error' => $this->text()->defaultValue(null),
        ]);

        $this->createIndex('domain', '{{%source_block}}', ['domain'], true);

        $this->addForeignKey(
            'fk-collection_error-collection_run_id',
            '{{%collection_error}}',
            ['collection_run_id'],
            '{{%collection_run}}',
            ['id'],
            'CASCADE',
            'CASCADE'
        );

        $this->addForeignKey(
            'fk-collection_run-industry_id',
            '{{%collection_run}}',
            ['industry_id'],
            '{{%industry_config}}',
            ['industry_id'],
            'CASCADE',
            'CASCADE'
        );

    }

    public function safeDown(): void
    {
        $this->dropForeignKey('fk-collection_error-collection_run_id', '{{%collection_error}}');
        $this->dropForeignKey('fk-collection_run-industry_id', '{{%collection_run}}');

        $this->dropTable('{{%source_block}}');
        $this->dropTable('{{%collection_error}}');
        $this->dropTable('{{%collection_run}}');
        $this->dropTable('{{%industry_config}}');
    }
}
