<?php

declare(strict_types=1);

use yii\db\Expression;
use yii\db\Migration;

/**
 * Squashed migration combining all previous migrations.
 *
 * This migration was auto-generated by squash-migrations command.
 *
 * Squashed migrations:
 *   - m251230_230723_add_audit_columns_to_industry_config.php
 *   - m251230_231040_squashed_schema.php
 *   - m260101_133022_create_dossier_schema.php
 *   - m260101_200000_create_peer_group_schema.php
 */
class m260101_175405_squashed_schema extends Migration
{
    public function safeUp(): void
    {
        // Table: collection_error
        $this->createTable('{{%collection_error}}', [
            'id' => $this->primaryKey(),
            'collection_run_id' => $this->integer()->notNull(),
            'severity' => $this->string(20)->notNull()->defaultValue('error'),
            'error_code' => $this->string(64)->notNull(),
            'error_message' => $this->text()->notNull(),
            'error_path' => $this->string(255)->defaultValue(null),
            'ticker' => $this->string(20)->defaultValue(null),
            'created_at' => $this->timestamp()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
        ]);

        // Table: collection_run
        $this->createTable('{{%collection_run}}', [
            'id' => $this->primaryKey(),
            'industry_id' => $this->string(64)->notNull(),
            'datapack_id' => $this->string(36)->notNull(),
            'status' => $this->string(20)->notNull()->defaultValue('pending'),
            'started_at' => $this->timestamp()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
            'completed_at' => $this->timestamp()->defaultValue(null),
            'companies_total' => $this->integer()->notNull()->defaultValue(0),
            'companies_success' => $this->integer()->notNull()->defaultValue(0),
            'companies_failed' => $this->integer()->notNull()->defaultValue(0),
            'gate_passed' => $this->tinyInteger()->defaultValue(null),
            'error_count' => $this->integer()->notNull()->defaultValue(0),
            'warning_count' => $this->integer()->notNull()->defaultValue(0),
            'file_path' => $this->string(512)->defaultValue(null),
            'file_size_bytes' => $this->bigInteger()->defaultValue(null),
            'duration_seconds' => $this->integer()->defaultValue(null),
        ]);

        $this->createIndex('datapack_id', '{{%collection_run}}', ['datapack_id'], true);

        // Table: source_block
        $this->createTable('{{%source_block}}', [
            'id' => $this->primaryKey(),
            'domain' => $this->string(255)->notNull(),
            'blocked_at' => $this->timestamp()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
            'blocked_until' => $this->timestamp()->notNull(),
            'consecutive_count' => $this->integer()->notNull()->defaultValue(1),
            'last_status_code' => $this->integer()->defaultValue(null),
            'last_error' => $this->text()->defaultValue(null),
        ]);

        $this->createIndex('domain', '{{%source_block}}', ['domain'], true);

        // Table: annual_financial
        $this->createTable('{{%annual_financial}}', [
            'id' => $this->bigPrimaryKey()->unsigned(),
            'company_id' => $this->bigInteger()->notNull()->unsigned(),
            'fiscal_year' => $this->smallInteger()->notNull()->unsigned(),
            'period_end_date' => $this->date()->notNull(),
            'revenue' => $this->decimal(20, 2)->defaultValue(null),
            'cost_of_revenue' => $this->decimal(20, 2)->defaultValue(null),
            'gross_profit' => $this->decimal(20, 2)->defaultValue(null),
            'operating_income' => $this->decimal(20, 2)->defaultValue(null),
            'ebitda' => $this->decimal(20, 2)->defaultValue(null),
            'net_income' => $this->decimal(20, 2)->defaultValue(null),
            'eps' => $this->decimal(10, 4)->defaultValue(null),
            'operating_cash_flow' => $this->decimal(20, 2)->defaultValue(null),
            'capex' => $this->decimal(20, 2)->defaultValue(null),
            'free_cash_flow' => $this->decimal(20, 2)->defaultValue(null),
            'dividends_paid' => $this->decimal(20, 2)->defaultValue(null),
            'total_assets' => $this->decimal(20, 2)->defaultValue(null),
            'total_liabilities' => $this->decimal(20, 2)->defaultValue(null),
            'total_equity' => $this->decimal(20, 2)->defaultValue(null),
            'total_debt' => $this->decimal(20, 2)->defaultValue(null),
            'cash_and_equivalents' => $this->decimal(20, 2)->defaultValue(null),
            'net_debt' => $this->decimal(20, 2)->defaultValue(null),
            'shares_outstanding' => $this->bigInteger()->defaultValue(null)->unsigned(),
            'currency' => $this->string()->notNull(),
            'source_adapter' => $this->string(50)->notNull(),
            'source_url' => $this->string(500)->defaultValue(null),
            'collected_at' => $this->dateTime()->notNull(),
            'version' => $this->tinyInteger()->notNull()->defaultValue(1)->unsigned(),
            'is_current' => $this->tinyInteger()->notNull()->defaultValue(1),
            'created_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
        ]);

        $this->createIndex('uk_company_year_version', '{{%annual_financial}}', ['company_id', 'fiscal_year', 'version'], true);

        // Table: collection_attempt
        $this->createTable('{{%collection_attempt}}', [
            'id' => $this->bigPrimaryKey()->unsigned(),
            'entity_type' => $this->string(255)->notNull(),
            'entity_id' => $this->bigInteger()->defaultValue(null)->unsigned(),
            'data_type' => $this->string(50)->notNull(),
            'source_adapter' => $this->string(50)->notNull(),
            'source_url' => $this->string(500)->notNull(),
            'outcome' => $this->string(255)->notNull(),
            'http_status' => $this->smallInteger()->defaultValue(null)->unsigned(),
            'error_message' => $this->string(500)->defaultValue(null),
            'attempted_at' => $this->dateTime()->notNull(),
            'duration_ms' => $this->integer()->defaultValue(null)->unsigned(),
            'created_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
        ]);

        // Table: collection_policy
        $this->createTable('{{%collection_policy}}', [
            'id' => $this->bigPrimaryKey()->unsigned(),
            'slug' => $this->string(100)->notNull(),
            'name' => $this->string(100)->notNull(),
            'description' => $this->string(500)->defaultValue(null),
            'history_years' => $this->tinyInteger()->notNull()->defaultValue(5)->unsigned(),
            'quarters_to_fetch' => $this->tinyInteger()->notNull()->defaultValue(8)->unsigned(),
            'valuation_metrics' => $this->json()->notNull(),
            'annual_financial_metrics' => $this->json()->defaultValue(null),
            'quarterly_financial_metrics' => $this->json()->defaultValue(null),
            'operational_metrics' => $this->json()->defaultValue(null),
            'commodity_benchmark' => $this->string(50)->defaultValue(null),
            'margin_proxy' => $this->string(50)->defaultValue(null),
            'sector_index' => $this->string(50)->defaultValue(null),
            'required_indicators' => $this->json()->defaultValue(null),
            'optional_indicators' => $this->json()->defaultValue(null),
            'is_default_for_sector' => $this->string(100)->defaultValue(null),
            'created_by' => $this->string(100)->defaultValue(null),
            'updated_by' => $this->string(100)->defaultValue(null),
            'created_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
            'updated_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')),
        ]);

        $this->createIndex('slug', '{{%collection_policy}}', ['slug'], true);
        $this->createIndex('uk_sector_default', '{{%collection_policy}}', ['is_default_for_sector'], true);

        // Table: company
        $this->createTable('{{%company}}', [
            'id' => $this->bigPrimaryKey()->unsigned(),
            'ticker' => $this->string(20)->notNull(),
            'exchange' => $this->string(20)->defaultValue(null),
            'name' => $this->string(255)->defaultValue(null),
            'sector' => $this->string(100)->defaultValue(null),
            'industry' => $this->string(100)->defaultValue(null),
            'currency' => $this->string()->defaultValue(null),
            'fiscal_year_end' => $this->tinyInteger()->defaultValue(null)->unsigned(),
            'financials_collected_at' => $this->dateTime()->defaultValue(null),
            'quarters_collected_at' => $this->dateTime()->defaultValue(null),
            'valuation_collected_at' => $this->dateTime()->defaultValue(null),
            'profile_collected_at' => $this->dateTime()->defaultValue(null),
            'created_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
            'updated_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
        ]);

        $this->createIndex('uk_ticker', '{{%company}}', ['ticker'], true);

        // Table: data_gap
        $this->createTable('{{%data_gap}}', [
            'id' => $this->bigPrimaryKey()->unsigned(),
            'company_id' => $this->bigInteger()->notNull()->unsigned(),
            'data_type' => $this->string(50)->notNull(),
            'gap_reason' => $this->string(255)->notNull(),
            'first_detected' => $this->dateTime()->notNull(),
            'last_checked' => $this->dateTime()->notNull(),
            'check_count' => $this->integer()->notNull()->defaultValue(1)->unsigned(),
            'notes' => $this->string(500)->defaultValue(null),
            'created_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
            'updated_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
        ]);

        $this->createIndex('uk_company_gap', '{{%data_gap}}', ['company_id', 'data_type'], true);

        // Table: fx_rate
        $this->createTable('{{%fx_rate}}', [
            'id' => $this->bigPrimaryKey()->unsigned(),
            'base_currency' => $this->string()->notNull(),
            'quote_currency' => $this->string()->notNull(),
            'rate_date' => $this->date()->notNull(),
            'rate' => $this->decimal(12, 6)->notNull(),
            'source_adapter' => $this->string(50)->notNull()->defaultValue('ecb'),
            'collected_at' => $this->dateTime()->notNull(),
            'created_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
        ]);

        $this->createIndex('uk_pair_date', '{{%fx_rate}}', ['base_currency', 'quote_currency', 'rate_date'], true);

        // Table: industry_peer_group
        $this->createTable('{{%industry_peer_group}}', [
            'id' => $this->bigPrimaryKey()->unsigned(),
            'slug' => $this->string(100)->notNull(),
            'name' => $this->string(255)->notNull(),
            'description' => $this->string(500)->defaultValue(null),
            'sector' => $this->string(100)->notNull(),
            'policy_id' => $this->bigInteger()->defaultValue(null)->unsigned(),
            'is_active' => $this->tinyInteger()->notNull()->defaultValue(1),
            'created_by' => $this->string(100)->defaultValue(null),
            'updated_by' => $this->string(100)->defaultValue(null),
            'created_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
            'updated_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')),
        ]);

        $this->createIndex('slug', '{{%industry_peer_group}}', ['slug'], true);
        $this->createIndex('idx_sector', '{{%industry_peer_group}}', ['sector']);
        $this->createIndex('idx_is_active', '{{%industry_peer_group}}', ['is_active']);

        // Table: industry_peer_group_member
        $this->createTable('{{%industry_peer_group_member}}', [
            'peer_group_id' => $this->bigInteger()->notNull()->unsigned(),
            'company_id' => $this->bigInteger()->notNull()->unsigned(),
            'is_focal' => $this->tinyInteger()->notNull()->defaultValue(0),
            'display_order' => $this->smallInteger()->notNull()->defaultValue(0)->unsigned(),
            'added_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
            'added_by' => $this->string(100)->defaultValue(null),
            'PRIMARY KEY (peer_group_id, company_id)',
        ]);

        $this->createIndex('idx_company', '{{%industry_peer_group_member}}', ['company_id']);
        $this->createIndex('idx_focal', '{{%industry_peer_group_member}}', ['is_focal']);

        // Table: macro_indicator
        $this->createTable('{{%macro_indicator}}', [
            'id' => $this->bigPrimaryKey()->unsigned(),
            'indicator_key' => $this->string(100)->notNull(),
            'indicator_date' => $this->date()->notNull(),
            'value' => $this->decimal(20, 4)->notNull(),
            'unit' => $this->string(50)->notNull(),
            'source_adapter' => $this->string(50)->notNull(),
            'source_url' => $this->string(500)->defaultValue(null),
            'collected_at' => $this->dateTime()->notNull(),
            'created_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
        ]);

        $this->createIndex('uk_indicator_date', '{{%macro_indicator}}', ['indicator_key', 'indicator_date'], true);

        // Table: price_history
        $this->createTable('{{%price_history}}', [
            'id' => $this->bigPrimaryKey()->unsigned(),
            'symbol' => $this->string(20)->notNull(),
            'symbol_type' => $this->string(255)->notNull(),
            'price_date' => $this->date()->notNull(),
            'open' => $this->decimal(12, 4)->defaultValue(null),
            'high' => $this->decimal(12, 4)->defaultValue(null),
            'low' => $this->decimal(12, 4)->defaultValue(null),
            'close' => $this->decimal(12, 4)->notNull(),
            'adjusted_close' => $this->decimal(12, 4)->defaultValue(null),
            'volume' => $this->bigInteger()->defaultValue(null)->unsigned(),
            'currency' => $this->string()->notNull()->defaultValue('USD'),
            'source_adapter' => $this->string(50)->notNull(),
            'collected_at' => $this->dateTime()->notNull(),
            'created_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
        ]);

        $this->createIndex('uk_symbol_date', '{{%price_history}}', ['symbol', 'price_date'], true);

        // Table: quarterly_financial
        $this->createTable('{{%quarterly_financial}}', [
            'id' => $this->bigPrimaryKey()->unsigned(),
            'company_id' => $this->bigInteger()->notNull()->unsigned(),
            'fiscal_year' => $this->smallInteger()->notNull()->unsigned(),
            'fiscal_quarter' => $this->tinyInteger()->notNull()->unsigned(),
            'period_end_date' => $this->date()->notNull(),
            'revenue' => $this->decimal(20, 2)->defaultValue(null),
            'gross_profit' => $this->decimal(20, 2)->defaultValue(null),
            'operating_income' => $this->decimal(20, 2)->defaultValue(null),
            'ebitda' => $this->decimal(20, 2)->defaultValue(null),
            'net_income' => $this->decimal(20, 2)->defaultValue(null),
            'eps' => $this->decimal(10, 4)->defaultValue(null),
            'operating_cash_flow' => $this->decimal(20, 2)->defaultValue(null),
            'capex' => $this->decimal(20, 2)->defaultValue(null),
            'free_cash_flow' => $this->decimal(20, 2)->defaultValue(null),
            'currency' => $this->string()->notNull(),
            'source_adapter' => $this->string(50)->notNull(),
            'source_url' => $this->string(500)->defaultValue(null),
            'collected_at' => $this->dateTime()->notNull(),
            'version' => $this->tinyInteger()->notNull()->defaultValue(1)->unsigned(),
            'is_current' => $this->tinyInteger()->notNull()->defaultValue(1),
            'created_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
        ]);

        $this->createIndex('uk_company_quarter_version', '{{%quarterly_financial}}', ['company_id', 'fiscal_year', 'fiscal_quarter', 'version'], true);

        // Table: ttm_financial
        $this->createTable('{{%ttm_financial}}', [
            'id' => $this->bigPrimaryKey()->unsigned(),
            'company_id' => $this->bigInteger()->notNull()->unsigned(),
            'as_of_date' => $this->date()->notNull(),
            'revenue' => $this->decimal(20, 2)->defaultValue(null),
            'gross_profit' => $this->decimal(20, 2)->defaultValue(null),
            'operating_income' => $this->decimal(20, 2)->defaultValue(null),
            'ebitda' => $this->decimal(20, 2)->defaultValue(null),
            'net_income' => $this->decimal(20, 2)->defaultValue(null),
            'operating_cash_flow' => $this->decimal(20, 2)->defaultValue(null),
            'capex' => $this->decimal(20, 2)->defaultValue(null),
            'free_cash_flow' => $this->decimal(20, 2)->defaultValue(null),
            'q1_period_end' => $this->date()->defaultValue(null),
            'q2_period_end' => $this->date()->defaultValue(null),
            'q3_period_end' => $this->date()->defaultValue(null),
            'q4_period_end' => $this->date()->defaultValue(null),
            'currency' => $this->string()->notNull(),
            'calculated_at' => $this->dateTime()->notNull(),
            'created_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
        ]);

        $this->createIndex('uk_company_date', '{{%ttm_financial}}', ['company_id', 'as_of_date'], true);

        // Table: valuation_snapshot
        $this->createTable('{{%valuation_snapshot}}', [
            'id' => $this->bigPrimaryKey()->unsigned(),
            'company_id' => $this->bigInteger()->notNull()->unsigned(),
            'snapshot_date' => $this->date()->notNull(),
            'price' => $this->decimal(12, 4)->defaultValue(null),
            'market_cap' => $this->decimal(20, 2)->defaultValue(null),
            'enterprise_value' => $this->decimal(20, 2)->defaultValue(null),
            'shares_outstanding' => $this->bigInteger()->defaultValue(null)->unsigned(),
            'trailing_pe' => $this->decimal(10, 4)->defaultValue(null),
            'forward_pe' => $this->decimal(10, 4)->defaultValue(null),
            'peg_ratio' => $this->decimal(10, 4)->defaultValue(null),
            'price_to_book' => $this->decimal(10, 4)->defaultValue(null),
            'price_to_sales' => $this->decimal(10, 4)->defaultValue(null),
            'ev_to_ebitda' => $this->decimal(10, 4)->defaultValue(null),
            'ev_to_revenue' => $this->decimal(10, 4)->defaultValue(null),
            'dividend_yield' => $this->decimal(8, 4)->defaultValue(null),
            'fcf_yield' => $this->decimal(8, 4)->defaultValue(null),
            'earnings_yield' => $this->decimal(8, 4)->defaultValue(null),
            'net_debt_to_ebitda' => $this->decimal(10, 4)->defaultValue(null),
            'retention_tier' => $this->string(255)->notNull()->defaultValue('daily'),
            'currency' => $this->string()->notNull(),
            'source_adapter' => $this->string(50)->notNull(),
            'collected_at' => $this->dateTime()->notNull(),
            'created_at' => $this->dateTime()->notNull()->defaultValue(new Expression('CURRENT_TIMESTAMP')),
        ]);

        $this->createIndex('uk_company_date', '{{%valuation_snapshot}}', ['company_id', 'snapshot_date'], true);

        $this->addForeignKey(
            'fk-collection_error-collection_run_id',
            '{{%collection_error}}',
            ['collection_run_id'],
            '{{%collection_run}}',
            ['id'],
            'CASCADE',
            'CASCADE'
        );

        $this->addForeignKey(
            'fk-collection_run-industry_id',
            '{{%collection_run}}',
            ['industry_id'],
            '{{%industry_peer_group}}',
            ['slug'],
            'CASCADE',
            'CASCADE'
        );

        $this->addForeignKey(
            'annual_financial_ibfk_1',
            '{{%annual_financial}}',
            ['company_id'],
            '{{%company}}',
            ['id'],
            'CASCADE',
            'CASCADE'
        );

        $this->addForeignKey(
            'data_gap_ibfk_1',
            '{{%data_gap}}',
            ['company_id'],
            '{{%company}}',
            ['id'],
            'CASCADE',
            'CASCADE'
        );

        $this->addForeignKey(
            'industry_peer_group_ibfk_1',
            '{{%industry_peer_group}}',
            ['policy_id'],
            '{{%collection_policy}}',
            ['id'],
            'SET NULL',
            'CASCADE'
        );

        $this->addForeignKey(
            'industry_peer_group_member_ibfk_1',
            '{{%industry_peer_group_member}}',
            ['peer_group_id'],
            '{{%industry_peer_group}}',
            ['id'],
            'CASCADE',
            'CASCADE'
        );

        $this->addForeignKey(
            'industry_peer_group_member_ibfk_2',
            '{{%industry_peer_group_member}}',
            ['company_id'],
            '{{%company}}',
            ['id'],
            'CASCADE',
            'CASCADE'
        );

        $this->addForeignKey(
            'quarterly_financial_ibfk_1',
            '{{%quarterly_financial}}',
            ['company_id'],
            '{{%company}}',
            ['id'],
            'CASCADE',
            'CASCADE'
        );

        $this->addForeignKey(
            'ttm_financial_ibfk_1',
            '{{%ttm_financial}}',
            ['company_id'],
            '{{%company}}',
            ['id'],
            'CASCADE',
            'CASCADE'
        );

        $this->addForeignKey(
            'valuation_snapshot_ibfk_1',
            '{{%valuation_snapshot}}',
            ['company_id'],
            '{{%company}}',
            ['id'],
            'CASCADE',
            'CASCADE'
        );

    }

    public function safeDown(): void
    {
        $this->dropForeignKey('fk-collection_error-collection_run_id', '{{%collection_error}}');
        $this->dropForeignKey('fk-collection_run-industry_id', '{{%collection_run}}');
        $this->dropForeignKey('annual_financial_ibfk_1', '{{%annual_financial}}');
        $this->dropForeignKey('data_gap_ibfk_1', '{{%data_gap}}');
        $this->dropForeignKey('industry_peer_group_ibfk_1', '{{%industry_peer_group}}');
        $this->dropForeignKey('industry_peer_group_member_ibfk_1', '{{%industry_peer_group_member}}');
        $this->dropForeignKey('industry_peer_group_member_ibfk_2', '{{%industry_peer_group_member}}');
        $this->dropForeignKey('quarterly_financial_ibfk_1', '{{%quarterly_financial}}');
        $this->dropForeignKey('ttm_financial_ibfk_1', '{{%ttm_financial}}');
        $this->dropForeignKey('valuation_snapshot_ibfk_1', '{{%valuation_snapshot}}');

        $this->dropTable('{{%valuation_snapshot}}');
        $this->dropTable('{{%ttm_financial}}');
        $this->dropTable('{{%quarterly_financial}}');
        $this->dropTable('{{%price_history}}');
        $this->dropTable('{{%macro_indicator}}');
        $this->dropTable('{{%industry_peer_group_member}}');
        $this->dropTable('{{%industry_peer_group}}');
        $this->dropTable('{{%fx_rate}}');
        $this->dropTable('{{%data_gap}}');
        $this->dropTable('{{%collection_policy}}');
        $this->dropTable('{{%collection_attempt}}');
        $this->dropTable('{{%annual_financial}}');
        $this->dropTable('{{%company}}');
        $this->dropTable('{{%source_block}}');
        $this->dropTable('{{%collection_error}}');
        $this->dropTable('{{%collection_run}}');
    }
}
