#!/usr/bin/env php
<?php

use yii\console\Application;

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new Application($config);
exit($application->run());

